/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WellbeingRouteImport } from './routes/wellbeing'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppWellbeingRouteImport } from './routes/app/wellbeing'
import { Route as AppVisitRouteImport } from './routes/app/visit'
import { Route as AppUsersRouteImport } from './routes/app/users'
import { Route as AppScheduleRouteImport } from './routes/app/schedule'
import { Route as AppMessagesRouteImport } from './routes/app/messages'
import { Route as AppIncidentsRouteImport } from './routes/app/incidents'
import { Route as AppExceptionsRouteImport } from './routes/app/exceptions'
import { Route as AppDeletedRouteImport } from './routes/app/deleted'
import { Route as AppClientsRouteImport } from './routes/app/clients'
import { Route as AppCarePlanRouteImport } from './routes/app/care-plan'
import { Route as AppActivityRouteImport } from './routes/app/activity'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AppClientsClientIdRouteImport } from './routes/app/clients.$clientId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const WellbeingRoute = WellbeingRouteImport.update({
  id: '/wellbeing',
  path: '/wellbeing',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWellbeingRoute = AppWellbeingRouteImport.update({
  id: '/wellbeing',
  path: '/wellbeing',
  getParentRoute: () => AppRoute,
} as any)
const AppVisitRoute = AppVisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsRoute = AppIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AppRoute,
} as any)
const AppExceptionsRoute = AppExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => AppRoute,
} as any)
const AppDeletedRoute = AppDeletedRouteImport.update({
  id: '/deleted',
  path: '/deleted',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppCarePlanRoute = AppCarePlanRouteImport.update({
  id: '/care-plan',
  path: '/care-plan',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppClientsClientIdRoute = AppClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => AppClientsRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wellbeing': typeof WellbeingRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app/activity': typeof AppActivityRoute
  '/app/care-plan': typeof AppCarePlanRoute
  '/app/clients': typeof AppClientsRouteWithChildren
  '/app/deleted': typeof AppDeletedRoute
  '/app/exceptions': typeof AppExceptionsRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/users': typeof AppUsersRoute
  '/app/visit': typeof AppVisitRoute
  '/app/wellbeing': typeof AppWellbeingRoute
  '/app/': typeof AppIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/clients/$clientId': typeof AppClientsClientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wellbeing': typeof WellbeingRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app/activity': typeof AppActivityRoute
  '/app/care-plan': typeof AppCarePlanRoute
  '/app/clients': typeof AppClientsRouteWithChildren
  '/app/deleted': typeof AppDeletedRoute
  '/app/exceptions': typeof AppExceptionsRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/users': typeof AppUsersRoute
  '/app/visit': typeof AppVisitRoute
  '/app/wellbeing': typeof AppWellbeingRoute
  '/app': typeof AppIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/clients/$clientId': typeof AppClientsClientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wellbeing': typeof WellbeingRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app/activity': typeof AppActivityRoute
  '/app/care-plan': typeof AppCarePlanRoute
  '/app/clients': typeof AppClientsRouteWithChildren
  '/app/deleted': typeof AppDeletedRoute
  '/app/exceptions': typeof AppExceptionsRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/users': typeof AppUsersRoute
  '/app/visit': typeof AppVisitRoute
  '/app/wellbeing': typeof AppWellbeingRoute
  '/app/': typeof AppIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/clients/$clientId': typeof AppClientsClientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/login'
    | '/mcp'
    | '/signup'
    | '/sitemap.xml'
    | '/wellbeing'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app/activity'
    | '/app/care-plan'
    | '/app/clients'
    | '/app/deleted'
    | '/app/exceptions'
    | '/app/incidents'
    | '/app/messages'
    | '/app/schedule'
    | '/app/users'
    | '/app/visit'
    | '/app/wellbeing'
    | '/app/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/clients/$clientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/login'
    | '/mcp'
    | '/signup'
    | '/sitemap.xml'
    | '/wellbeing'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app/activity'
    | '/app/care-plan'
    | '/app/clients'
    | '/app/deleted'
    | '/app/exceptions'
    | '/app/incidents'
    | '/app/messages'
    | '/app/schedule'
    | '/app/users'
    | '/app/visit'
    | '/app/wellbeing'
    | '/app'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/clients/$clientId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/login'
    | '/mcp'
    | '/signup'
    | '/sitemap.xml'
    | '/wellbeing'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app/activity'
    | '/app/care-plan'
    | '/app/clients'
    | '/app/deleted'
    | '/app/exceptions'
    | '/app/incidents'
    | '/app/messages'
    | '/app/schedule'
    | '/app/users'
    | '/app/visit'
    | '/app/wellbeing'
    | '/app/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/clients/$clientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WellbeingRoute: typeof WellbeingRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wellbeing': {
      id: '/wellbeing'
      path: '/wellbeing'
      fullPath: '/wellbeing'
      preLoaderRoute: typeof WellbeingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wellbeing': {
      id: '/app/wellbeing'
      path: '/wellbeing'
      fullPath: '/app/wellbeing'
      preLoaderRoute: typeof AppWellbeingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/visit': {
      id: '/app/visit'
      path: '/visit'
      fullPath: '/app/visit'
      preLoaderRoute: typeof AppVisitRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/schedule': {
      id: '/app/schedule'
      path: '/schedule'
      fullPath: '/app/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/incidents': {
      id: '/app/incidents'
      path: '/incidents'
      fullPath: '/app/incidents'
      preLoaderRoute: typeof AppIncidentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exceptions': {
      id: '/app/exceptions'
      path: '/exceptions'
      fullPath: '/app/exceptions'
      preLoaderRoute: typeof AppExceptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/deleted': {
      id: '/app/deleted'
      path: '/deleted'
      fullPath: '/app/deleted'
      preLoaderRoute: typeof AppDeletedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/care-plan': {
      id: '/app/care-plan'
      path: '/care-plan'
      fullPath: '/app/care-plan'
      preLoaderRoute: typeof AppCarePlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/clients/$clientId': {
      id: '/app/clients/$clientId'
      path: '/$clientId'
      fullPath: '/app/clients/$clientId'
      preLoaderRoute: typeof AppClientsClientIdRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppClientsRouteChildren {
  AppClientsClientIdRoute: typeof AppClientsClientIdRoute
}

const AppClientsRouteChildren: AppClientsRouteChildren = {
  AppClientsClientIdRoute: AppClientsClientIdRoute,
}

const AppClientsRouteWithChildren = AppClientsRoute._addFileChildren(
  AppClientsRouteChildren,
)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppCarePlanRoute: typeof AppCarePlanRoute
  AppClientsRoute: typeof AppClientsRouteWithChildren
  AppDeletedRoute: typeof AppDeletedRoute
  AppExceptionsRoute: typeof AppExceptionsRoute
  AppIncidentsRoute: typeof AppIncidentsRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppUsersRoute: typeof AppUsersRoute
  AppVisitRoute: typeof AppVisitRoute
  AppWellbeingRoute: typeof AppWellbeingRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppCarePlanRoute: AppCarePlanRoute,
  AppClientsRoute: AppClientsRouteWithChildren,
  AppDeletedRoute: AppDeletedRoute,
  AppExceptionsRoute: AppExceptionsRoute,
  AppIncidentsRoute: AppIncidentsRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppUsersRoute: AppUsersRoute,
  AppVisitRoute: AppVisitRoute,
  AppWellbeingRoute: AppWellbeingRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WellbeingRoute: WellbeingRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
